services:
  - type: web
    name: tg-bot-viotp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py # Đổi thành tên file chính của bạn nếu không phải bot.py
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      # Thêm các biến môi trường khác nếu bot của bạn cần (API keys, Token...)
      # - key: TELEGRAM_TOKEN
      #   value: "YOUR_TOKEN_HERE"
